sudo: required
services:
        - docker
        
before_install:
        - docker build -t deepti0905/docker-react -f Dockerfile.dev . 
         

script:
        - docker run deepti0905/docker-react npm run test -- --coverage 
